# Generated by Django 5.0.6 on 2024-06-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salaire',
            field=models.CharField(default='usser1', max_length=50),
        ),
    ]
