# Generated by Django 5.0.6 on 2024-06-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_leaverequest_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='username',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.TextField(default='username'),
        ),
    ]
