# Generated by Django 5.0.6 on 2024-06-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_actiondemande_delete_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondemande',
            name='user',
            field=models.CharField(default='username1', max_length=100),
        ),
    ]
