# Generated by Django 5.0.6 on 2024-06-18 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_employe_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequestAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='username')),
                ('number_of_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='title', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
