# Generated by Django 5.0.6 on 2024-05-31 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(default='usser1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='usser1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='usser1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='myCompany123', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='usser1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='usser1', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='usser1', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(default='usser1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='usser1', max_length=255),
        ),
    ]
