# Generated by Django 5.0.6 on 2024-06-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_employe_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
