# Generated by Django 5.0.6 on 2024-06-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_employe_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to=''),
        ),
    ]
