# Generated by Django 5.0.6 on 2024-06-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_employe_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='profile_image',
        ),
    ]
