# Generated by Django 5.0.6 on 2024-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_employe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
