# Generated by Django 5.0.6 on 2024-06-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_actiondemande_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondemande',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
