# Generated by Django 5.0.6 on 2024-06-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_employe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('user', models.CharField(default='username1', max_length=100)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.leaverequest')),
            ],
        ),
    ]
