# Generated by Django 5.0.6 on 2024-06-01 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_gender_user_adresse_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_de_naissance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
    ]
