# Generated by Django 5.0.6 on 2024-06-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_user_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salaire',
            field=models.IntegerField(default=0),
        ),
    ]
