# Generated by Django 5.0.6 on 2024-06-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_employe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user',
        ),
    ]
