# Generated by Django 5.0.6 on 2024-06-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_actiondemande_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondemande',
            name='demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.leaverequest'),
        ),
    ]
