# Generated by Django 5.0.6 on 2024-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_actiondemande_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(default='usser1', max_length=255, unique=True),
        ),
    ]
