# Generated by Django 5.0.6 on 2024-06-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_actiondemande_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiondemande',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
