# Generated by Django 5.0.6 on 2024-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_actiondemande_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
