# Generated by Django 5.0.6 on 2024-06-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Num_Compte',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
