# Generated by Django 5.0.6 on 2024-06-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_profile_num_compte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Num_Compte',
        ),
    ]
