# Generated by Django 5.0.6 on 2024-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_remove_profile_num_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Num_Compte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
